import { Equipments } from "./equipments";
import { RecipeStepsActions } from "./recipeSteps";
import type { Equipment } from "../interfaces/Equipment";

export const EQUIPMENT_CATALOG: Record<Equipments, Equipment> = {
  [Equipments.CUP_STATION]: {
    id: Equipments.CUP_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.COFFEE_STATION]: {
    id: Equipments.COFFEE_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.TEA_STATION]: {
    id: Equipments.TEA_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.WATER_STATION]: {
    id: Equipments.WATER_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.MILK_STATION]: {
    id: Equipments.MILK_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.SODA_STATION]: {
    id: Equipments.SODA_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.JUICE_STATION]: {
    id: Equipments.JUICE_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.CHOCOLATE_STATION]: {
    id: Equipments.CHOCOLATE_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.ICE_STATION]: {
    id: Equipments.ICE_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.PREPARATION_STATION]: {
    id: Equipments.PREPARATION_STATION,
    actions: [RecipeStepsActions.ADD],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.MIXER]: {
    id: Equipments.MIXER,
    actions: [RecipeStepsActions.MIX],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.BLENDER]: {
    id: Equipments.BLENDER,
    actions: [RecipeStepsActions.BLEND],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.HEATING_STATION]: {
    id: Equipments.HEATING_STATION,
    actions: [RecipeStepsActions.HEAT],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.TOPPING_STATION]: {
    id: Equipments.TOPPING_STATION,
    actions: [RecipeStepsActions.TOP],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.CUP_SEALER]: {
    id: Equipments.CUP_SEALER,
    actions: [RecipeStepsActions.CLOSE],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.SERVING_COUNTER]: {
    id: Equipments.SERVING_COUNTER,
    actions: [RecipeStepsActions.SERVE],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
  [Equipments.TRASH_BIN]: {
    id: Equipments.TRASH_BIN,
    actions: [],
    purchasePrice: 0,
    requiredLevel: 1,
    duration: 0,
  },
};
