export enum Ingredients {
  CUP = "cup",
  COFFEE = "coffee",
  LID = "lid",
  TEA = "tea",
  ICE = "ice",
  WATER = "water",
  LEMON = "lemon",
  ORANGE_JUICE = "orange_juice",
  MILK = "milk",
  CHOCOLATE = "chocolate",
  ICE_CREAM = "ice_cream",
  SODA = "soda",
  HONEY = "honey",
  SUGAR = "sugar",
  STRAWBERRY = "strawberry",
  FOAM = "foam",
  PEACH = "peach",
  VANILLA = "vanilla",
  TAPIOCA = "tapioca",
  CINNAMON = "cinnamon",
  BANANA = "banana",
  WHIPPED_CREAM = "whipped_cream",
  SPRINKLES = "sprinkles",
  CARAMEL = "caramel",
  MANGO = "mango",
  PASSION_FRUIT = "passion_fruit",
  COOKIE = "cookie",
  RASPBERRY = "raspberry",
  SYRUP = "syrup",
}

export const INGREDIENTS_NAMES: Record<Ingredients, string> = {
  [Ingredients.CUP]: "Copo",
  [Ingredients.COFFEE]: "Café",
  [Ingredients.LID]: "Tampa",
  [Ingredients.TEA]: "Chá",
  [Ingredients.ICE]: "Gelo",
  [Ingredients.WATER]: "Água",
  [Ingredients.LEMON]: "Limão",
  [Ingredients.ORANGE_JUICE]: "Suco de laranja",
  [Ingredients.MILK]: "Leite",
  [Ingredients.CHOCOLATE]: "Chocolate",
  [Ingredients.ICE_CREAM]: "Sorvete",
  [Ingredients.SODA]: "Refrigerante",
  [Ingredients.HONEY]: "Mel",
  [Ingredients.SUGAR]: "Açúcar",
  [Ingredients.STRAWBERRY]: "Morango",
  [Ingredients.FOAM]: "Espuma",
  [Ingredients.PEACH]: "Pêssego",
  [Ingredients.VANILLA]: "Baunilha",
  [Ingredients.TAPIOCA]: "Tapioca",
  [Ingredients.CINNAMON]: "Canela",
  [Ingredients.BANANA]: "Banana",
  [Ingredients.WHIPPED_CREAM]: "Chantilly",
  [Ingredients.SPRINKLES]: "Confeitos",
  [Ingredients.CARAMEL]: "Caramelo",
  [Ingredients.MANGO]: "Manga",
  [Ingredients.PASSION_FRUIT]: "Maracujá",
  [Ingredients.COOKIE]: "Biscoito",
  [Ingredients.RASPBERRY]: "Framboesa",
  [Ingredients.SYRUP]: "Calda",
};
