import { Equipments } from "./equipments";

export const TILE_SIZE = 40;

export enum Tiles {
  NONE = -1,
  FLOOR = 0,
  WALL = 1,
  PREPARATION_STATION = 2,
  MIXER = 3,
  BLENDER = 4,
  HEATING_STATION = 5,
  TOPPING_STATION = 6,
  CUP_SEALER = 7,
  SERVING_COUNTER = 8,
  TRASH_BIN = 9,
  CUP_STATION = 10,
  COFFEE_STATION = 11,
  TEA_STATION = 12,
  WATER_STATION = 13,
  MILK_STATION = 14,
  SODA_STATION = 15,
  JUICE_STATION = 16,
  CHOCOLATE_STATION = 17,
  ICE_STATION = 18,
}

export const TILE_COLORS: Record<Tiles, string> = {
  [Tiles.NONE]: "transparent",
  [Tiles.FLOOR]: "#000000",
  [Tiles.WALL]: "transparent",
  [Tiles.PREPARATION_STATION]: "#c2410c",
  [Tiles.MIXER]: "#9333ea",
  [Tiles.BLENDER]: "#2563eb",
  [Tiles.HEATING_STATION]: "#dc2626",
  [Tiles.TOPPING_STATION]: "#db2777",
  [Tiles.CUP_SEALER]: "#0891b2",
  [Tiles.SERVING_COUNTER]: "#16a34a",
  [Tiles.TRASH_BIN]: "#4b5563",
  [Tiles.CUP_STATION]: "#eab308",
  [Tiles.COFFEE_STATION]: "#78350f",
  [Tiles.TEA_STATION]: "#4d7c0f",
  [Tiles.WATER_STATION]: "#0ea5e9",
  [Tiles.MILK_STATION]: "#f8fafc",
  [Tiles.SODA_STATION]: "#be123c",
  [Tiles.JUICE_STATION]: "#fb923c",
  [Tiles.CHOCOLATE_STATION]: "#451a03",
  [Tiles.ICE_STATION]: "#a5f3fc",
};

export const TILE_TO_EQUIPMENT: Partial<Record<Tiles, Equipments>> = {
  [Tiles.PREPARATION_STATION]: Equipments.PREPARATION_STATION,
  [Tiles.MIXER]: Equipments.MIXER,
  [Tiles.BLENDER]: Equipments.BLENDER,
  [Tiles.HEATING_STATION]: Equipments.HEATING_STATION,
  [Tiles.TOPPING_STATION]: Equipments.TOPPING_STATION,
  [Tiles.CUP_SEALER]: Equipments.CUP_SEALER,
  [Tiles.SERVING_COUNTER]: Equipments.SERVING_COUNTER,
  [Tiles.TRASH_BIN]: Equipments.TRASH_BIN,
  [Tiles.CUP_STATION]: Equipments.CUP_STATION,
  [Tiles.COFFEE_STATION]: Equipments.COFFEE_STATION,
  [Tiles.TEA_STATION]: Equipments.TEA_STATION,
  [Tiles.WATER_STATION]: Equipments.WATER_STATION,
  [Tiles.MILK_STATION]: Equipments.MILK_STATION,
  [Tiles.SODA_STATION]: Equipments.SODA_STATION,
  [Tiles.JUICE_STATION]: Equipments.JUICE_STATION,
  [Tiles.CHOCOLATE_STATION]: Equipments.CHOCOLATE_STATION,
  [Tiles.ICE_STATION]: Equipments.ICE_STATION,
};
